### ISSUE TITLE
Chore: 개발 환경 구축

### ISSUE THREAD

**Issue by yumzen** [TEAM-Encore/SPRING-BACKEND#1]
## 🍒 IssueName
개발 환경 구축

## 📝 Description
Docker compose, error handling, 패키지 구조, 엔티티 세팅, Querydsl 기본 세팅, Swagger 세팅 등의 개발 환경 구축

## 🌱 Todo
- [x]  docker 환경 구축
- [x]  error handling 구조 설게
- [x]   패키지 구조 및 엔티티 세팅
- [x]   baseentity 생성
- [x] Swagger 세팅
- [x] Querydsl 기본 세팅
