### ISSUE TITLE
Deploy: CI/CD 구축

### ISSUE THREAD

**Issue by yumzen** [TEAM-Encore/SPRING-BACKEND#6]
## 🍒 IssueName
>  CI/CD 구축

## 📝 Description
>  CI/CD 구축

## 🌱 Todo
- [x] EC2 및 RDS 환경 설정
- [x] docker-compose로 프로젝트 배포
- [x] GitHub Action으로 CI/CD 구축
